{application,blockchain,
             [{applications,[kernel,stdlib,elixir,logger,poison]},
              {description,"blockchain"},
              {modules,['Elixir.Block','Elixir.BlockSupervisor',
                        'Elixir.Blockchain','Elixir.BlockchainApp',
                        'Elixir.BlockchainSupervisor','Elixir.Crypto']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.BlockchainApp',[]}}]}.
